### ISSUE TITLE
Fix image on README

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/xref_runner#31]

**Comment by hkasera** [comment]
@elbrujohalcon What is the expected image here? If you could point me to the image, I can send a PR for the fix :)

**Comment by elbrujohalcon** [comment]
@hkasera that's exactly the issue… it used to be something along the lines of…
![Michael Cera on Juno](http://cdn23.us1.fansshare.com/photos/michaelcera/juno-screencap-michael-cera-wallpaper-1786435769.jpg)
…but that's probably not available for public usage.
A _nerd_ runner… that's the idea! :)

**Comment by hkasera** [comment]
Hmm how about this one.

<img src="https://s-media-cache-ak0.pinimg.com/236x/26/58/96/2658968956497eb580b27c570e94556e.jpg" />

It is based on this animated series https://en.wikipedia.org/wiki/The_Road_Runner_Show

**Comment by elbrujohalcon** [comment]
HA! Yes, of course, I know the RoadRunner… I'm actually more of a coyote fan, myself. I even think that Coyote give us a much better representation of what this library is all about… you know… dealing with weird (but powerful) libraries to find very elusive bugs.
I would certainly accept a PR with a pic of Willie E. Coyote in the README, @hkasera .

**Comment by l33tLumberjack** [comment]
@elbrujohalcon Made pull request #63 to solve for this
