### ISSUE TITLE
Broken for modules created with Elixir

### ISSUE THREAD

**Issue by x4lldux** [inaka/xref_runner#52]
Running `check` on any Elixir module throws:

```
** (MatchError) no match of right hand side value: [{:attribute, 0, :compile, :no_auto_import}, {:attribute,....
```

By the looks of it, every Elixir module AST starts with `{:attribute, 0, :compile, :no_auto_import}` and also the first `file` attribute is not necessarily at 1st line.

**Comment by elbrujohalcon** [comment]
Fixed by #53
